insert into public.affirmations (text, age_band, pillar, sort_order) values
('I can speak up even when my voice shakes.', '10-12', 'confidence', 0),
('I am enough, exactly as I am right now.', '10-12', 'self-worth', 1),
('I can figure this out on my own.', '10-12', 'independence', 2),
('I get back up. That''s what I do.', '10-12', 'resilience', 3),
('My feelings are allowed, all of them.', '10-12', 'emotional-calm', 4),
('How I treat people matters more than being right.', '10-12', 'kindness-character', 5),
('I can start a conversation with someone new.', '10-12', 'friendship', 6),
('I notice the good stuff, not just the bad.', '10-12', 'gratitude', 7),
('I wonder about things, and I chase the answers.', '10-12', 'curiosity', 8),
('I am loved, no matter what kind of day I have.', '10-12', 'belonging', 9),
('A team wins when everyone does their job.', '10-12', 'teamwork', 10),
('My siblings annoy me sometimes and I still love them.', '10-12', 'sibling-love', 11),
('Doing my best matters more than being the best.', '10-12', 'responsibility', 12),
('Trying matters more than being good at it right away.', '10-12', 'confidence', 13),
('I don''t have to be perfect to be good.', '10-12', 'self-worth', 14),
('I don''t need someone to hold my hand through everything.', '10-12', 'independence', 15),
('A bad day is just a day, not my whole life.', '10-12', 'resilience', 16),
('I can feel angry without acting angry.', '10-12', 'emotional-calm', 17),
('I am kind even when no one is watching.', '10-12', 'kindness-character', 18),
('Being a good friend starts with listening.', '10-12', 'friendship', 19),
('I am thankful for the people who show up for me.', '10-12', 'gratitude', 20),
('Questions make me smarter, not slower.', '10-12', 'curiosity', 21),
('My family is my team.', '10-12', 'belonging', 22),
('I don''t have to be the star. I just have to show up.', '10-12', 'teamwork', 23),
('I have my brother''s back, no matter what.', '10-12', 'sibling-love', 24),
('I finish my homework even when I''d rather do something else.', '10-12', 'responsibility', 25),
('My ideas are worth saying out loud.', '10-12', 'confidence', 26),
('My worth isn''t measured by grades or likes.', '10-12', 'self-worth', 27),
('I can make my own decisions and live with them.', '10-12', 'independence', 28),
('I have survived every hard day so far.', '10-12', 'resilience', 29),
('It''s okay to need a minute.', '10-12', 'emotional-calm', 30),
('I stand up for people who can''t stand up for themselves.', '10-12', 'kindness-character', 31),
('I don''t need a huge group; real friends are enough.', '10-12', 'friendship', 32),
('Today has something in it worth appreciating.', '10-12', 'gratitude', 33),
('I don''t have to love every subject to learn from it.', '10-12', 'curiosity', 34),
('I belong here, exactly as I am.', '10-12', 'belonging', 35),
('Helping my sibling is not losing. It is what family does.', '10-12', 'teamwork', 36),
('My sister gets me in a way nobody else does.', '10-12', 'sibling-love', 37),
('People can count on me because I follow through.', '10-12', 'responsibility', 38),
('I don''t have to be the loudest to be heard.', '10-12', 'confidence', 39),
('I like who I am becoming.', '10-12', 'self-worth', 40),
('Asking for help is my choice, not my weakness.', '10-12', 'independence', 41),
('Falling down doesn''t make me a failure.', '10-12', 'resilience', 42),
('I breathe in and out until I feel steady.', '10-12', 'emotional-calm', 43),
('I do the right thing when it''s hard, not just when it''s easy.', '10-12', 'kindness-character', 44),
('I check in on my friends when they''re quiet.', '10-12', 'friendship', 45),
('I don''t take the small things for granted.', '10-12', 'gratitude', 46),
('Being curious is cooler than pretending to know.', '10-12', 'curiosity', 47),
('Home is where I don''t have to pretend.', '10-12', 'belonging', 48),
('I listen first, then I talk.', '10-12', 'teamwork', 49),
('We don''t have to like the same things to be close.', '10-12', 'sibling-love', 50),
('I do my chores well, not just fast.', '10-12', 'responsibility', 51),
('I can start before I feel ready.', '10-12', 'confidence', 52),
('I don''t need to be like anyone else.', '10-12', 'self-worth', 53),
('I can handle the small stuff without a reminder.', '10-12', 'independence', 54),
('I can start over as many times as I need to.', '10-12', 'resilience', 55),
('Feelings are visitors; they don''t move in forever.', '10-12', 'emotional-calm', 56),
('I apologize when I''m wrong, and I mean it.', '10-12', 'kindness-character', 57),
('I can join in without waiting for an invitation sometimes.', '10-12', 'friendship', 58),
('I say thanks out loud instead of just thinking it.', '10-12', 'gratitude', 59),
('I learn something new every day on purpose.', '10-12', 'curiosity', 60),
('I am wanted, not just tolerated.', '10-12', 'belonging', 61),
('When I do my chores, the whole house feels better.', '10-12', 'teamwork', 62),
('I can forgive my sibling and mean it.', '10-12', 'sibling-love', 63),
('When I say I''ll do something, I do it.', '10-12', 'responsibility', 64),
('Being nervous doesn''t mean I can''t do it.', '10-12', 'confidence', 65),
('There is no one else exactly like me, and that''s fine.', '10-12', 'self-worth', 66),
('I think for myself.', '10-12', 'independence', 67),
('Hard seasons end. I keep going.', '10-12', 'resilience', 68),
('I don''t have to fix my mood instantly.', '10-12', 'emotional-calm', 69),
('I don''t laugh at jokes that hurt people.', '10-12', 'kindness-character', 70),
('Good friends tell the truth kindly.', '10-12', 'friendship', 71),
('I am grateful for a body that lets me move and play.', '10-12', 'gratitude', 72),
('I read because it takes me places.', '10-12', 'curiosity', 73),
('My family has my back.', '10-12', 'belonging', 74),
('I can disagree without being mean about it.', '10-12', 'teamwork', 75),
('Being the oldest means setting the example.', '10-12', 'sibling-love', 76),
('I take care of my things so they last.', '10-12', 'responsibility', 77),
('I trust myself to handle what comes today.', '10-12', 'confidence', 78),
('I deserve the same kindness I give others.', '10-12', 'self-worth', 79),
('I can start something without being told to.', '10-12', 'independence', 80),
('I don''t quit on myself.', '10-12', 'resilience', 81),
('It''s okay to cry. It doesn''t make me weak.', '10-12', 'emotional-calm', 82),
('Being honest is worth the awkward moment.', '10-12', 'kindness-character', 83),
('I make room for people.', '10-12', 'friendship', 84),
('Even a regular day has good in it.', '10-12', 'gratitude', 85),
('I am not afraid to look dumb while learning.', '10-12', 'curiosity', 86),
('Love here isn''t something I have to earn.', '10-12', 'belonging', 87),
('Fair means everyone gets a turn, including me.', '10-12', 'teamwork', 88),
('Being the youngest doesn''t mean being the weakest.', '10-12', 'sibling-love', 89),
('Hard work feels good when it''s done.', '10-12', 'responsibility', 90),
('It''s okay to take up space.', '10-12', 'confidence', 91),
('I am not a problem to be fixed.', '10-12', 'self-worth', 92),
('My choices are mine to make.', '10-12', 'independence', 93),
('Disappointment won''t break me.', '10-12', 'resilience', 94),
('I can name what I feel, and that helps.', '10-12', 'emotional-calm', 95),
('I share credit when things go well.', '10-12', 'kindness-character', 96),
('I remember the little things about my friends.', '10-12', 'friendship', 97),
('I appreciate what I have instead of only wanting more.', '10-12', 'gratitude', 98),
('Mistakes in class mean my brain is working.', '10-12', 'curiosity', 99),
('I am part of something bigger than myself.', '10-12', 'belonging', 100),
('I ask for help instead of struggling alone.', '10-12', 'teamwork', 101),
('I listen when my brother needs to talk.', '10-12', 'sibling-love', 102),
('I don''t wait to be told twice.', '10-12', 'responsibility', 103),
('I don''t need permission to be myself.', '10-12', 'confidence', 104),
('What makes me different makes me interesting.', '10-12', 'self-worth', 105),
('I can solve problems without waiting to be rescued.', '10-12', 'independence', 106),
('I can feel sad and still keep moving.', '10-12', 'resilience', 107),
('I am not my worst feeling.', '10-12', 'emotional-calm', 108),
('I keep my promises, big and small.', '10-12', 'kindness-character', 109),
('I can disagree with a friend and still be friends.', '10-12', 'friendship', 110),
('I thank people who help me, even for little things.', '10-12', 'gratitude', 111),
('I ask "why" until I actually get it.', '10-12', 'curiosity', 112),
('Even when we fight, we still choose each other.', '10-12', 'belonging', 113),
('My friends count on me, and I count on them.', '10-12', 'teamwork', 114),
('My sister and I are stronger together.', '10-12', 'sibling-love', 115),
('My best effort is enough, and I give it.', '10-12', 'responsibility', 116),
('My opinion counts, even when it''s different.', '10-12', 'confidence', 117),
('I can be a work in progress and still be great.', '10-12', 'self-worth', 118),
('I learn by doing, not just by watching.', '10-12', 'independence', 119),
('What went wrong today teaches me something.', '10-12', 'resilience', 120),
('I can calm my body to calm my mind.', '10-12', 'emotional-calm', 121),
('I treat the new kid the way I''d want to be treated.', '10-12', 'kindness-character', 122),
('I don''t ditch people to look cool.', '10-12', 'friendship', 123),
('I am lucky in ways I sometimes forget.', '10-12', 'gratitude', 124),
('Learning isn''t just for school.', '10-12', 'curiosity', 125),
('I matter to my family in ways I can''t always see.', '10-12', 'belonging', 126),
('I clean up my mess so others don''t have to.', '10-12', 'teamwork', 127),
('It''s okay to need space from my siblings sometimes.', '10-12', 'sibling-love', 128),
('I clean up after myself without making it someone else''s job.', '10-12', 'responsibility', 129),
('I can ask the question everyone else is scared to ask.', '10-12', 'confidence', 130),
('I don''t have to prove myself to anyone today.', '10-12', 'self-worth', 131),
('I can take care of my own responsibilities.', '10-12', 'independence', 132),
('I am stronger than my worst moment.', '10-12', 'resilience', 133),
('Being upset is human, not shameful.', '10-12', 'emotional-calm', 134),
('Character is who I am when the teacher isn''t looking.', '10-12', 'kindness-character', 135),
('I am someone others feel safe around.', '10-12', 'friendship', 136),
('Gratitude turns an okay day into a good one.', '10-12', 'gratitude', 137),
('I try things I might be bad at.', '10-12', 'curiosity', 138),
('I am accepted here, mess and all.', '10-12', 'belonging', 139),
('Being a good teammate matters more than being the best player.', '10-12', 'teamwork', 140),
('I celebrate my brother''s wins like they''re mine.', '10-12', 'sibling-love', 141),
('I plan my time so homework gets done.', '10-12', 'responsibility', 142),
('I am allowed to change my mind.', '10-12', 'confidence', 143),
('Being me is not too much.', '10-12', 'self-worth', 144),
('I don''t need a crowd to know what''s right.', '10-12', 'independence', 145),
('I give myself more than one chance.', '10-12', 'resilience', 146),
('I give myself time to cool down before I speak.', '10-12', 'emotional-calm', 147),
('I don''t gossip, even when everyone else is.', '10-12', 'kindness-character', 148),
('I ask questions because I''m actually interested.', '10-12', 'friendship', 149),
('I notice when someone does something kind for me.', '10-12', 'gratitude', 150),
('I pay attention to how things work.', '10-12', 'curiosity', 151),
('My place in this family can''t be taken away.', '10-12', 'belonging', 152),
('I give credit when someone else does good work.', '10-12', 'teamwork', 153),
('We share a history nobody else has.', '10-12', 'sibling-love', 154),
('Small jobs done well build trust.', '10-12', 'responsibility', 155),
('Doing it badly the first time still counts as doing it.', '10-12', 'confidence', 156),
('I respect myself enough to rest when I need it.', '10-12', 'self-worth', 157),
('I can be alone without being lonely.', '10-12', 'independence', 158),
('Setbacks are part of getting better.', '10-12', 'resilience', 159),
('I don''t have to smile when I don''t feel like it.', '10-12', 'emotional-calm', 160),
('I help without being asked sometimes.', '10-12', 'kindness-character', 161),
('I give compliments that I actually mean.', '10-12', 'friendship', 162),
('I am thankful for second chances.', '10-12', 'gratitude', 163),
('I don''t need to be the smartest; I need to keep growing.', '10-12', 'curiosity', 164),
('I bring something to this family that no one else can.', '10-12', 'belonging', 165),
('At home I pull my weight. No one should do it all.', '10-12', 'teamwork', 166),
('I tell my sister the truth, kindly.', '10-12', 'sibling-love', 167),
('I take responsibility when I mess up.', '10-12', 'responsibility', 168),
('I don''t have to wait until I''m sure.', '10-12', 'confidence', 169);
insert into public.affirmations (text, age_band, pillar, sort_order) values
('I am allowed to take care of myself first sometimes.', '10-12', 'self-worth', 170),
('I do what I say I''ll do.', '10-12', 'independence', 171),
('I can handle "no" and keep going.', '10-12', 'resilience', 172),
('It''s okay to feel two things at once.', '10-12', 'emotional-calm', 173),
('I say thank you and I mean it.', '10-12', 'kindness-character', 174),
('I can handle it when plans don''t include me.', '10-12', 'friendship', 175),
('I appreciate my home and the people in it.', '10-12', 'gratitude', 176),
('I explore ideas that challenge me.', '10-12', 'curiosity', 177),
('It''s okay to need my people.', '10-12', 'belonging', 178),
('I am patient when my sibling gets on my nerves.', '10-12', 'teamwork', 179),
('My siblings saw me at my worst and stayed.', '10-12', 'sibling-love', 180),
('I do the boring parts too, not just the fun ones.', '10-12', 'responsibility', 181),
('My best is enough for today.', '10-12', 'confidence', 182),
('My value doesn''t go down when I mess up.', '10-12', 'self-worth', 183),
('I can plan my own time.', '10-12', 'independence', 184),
('I bend without breaking.', '10-12', 'resilience', 185),
('I can sit still with a big feeling.', '10-12', 'emotional-calm', 186),
('I include people instead of leaving them out.', '10-12', 'kindness-character', 187),
('I don''t keep score in friendships.', '10-12', 'friendship', 188),
('I don''t need something new to feel good.', '10-12', 'gratitude', 189),
('I finish what I start learning.', '10-12', 'curiosity', 190),
('I am rooted, even when life feels shaky.', '10-12', 'belonging', 191),
('We figure it out together instead of fighting about it.', '10-12', 'teamwork', 192),
('I make room for my little brother.', '10-12', 'sibling-love', 193),
('Being reliable is something I choose every day.', '10-12', 'responsibility', 194),
('I can stand by what I believe.', '10-12', 'confidence', 195),
('I don''t compare my behind-the-scenes to their highlight reel.', '10-12', 'self-worth', 196),
('I don''t fall apart when plans change.', '10-12', 'independence', 197),
('Tomorrow is a clean page.', '10-12', 'resilience', 198),
('My feelings give me information, not orders.', '10-12', 'emotional-calm', 199),
('I can be competitive without being cruel.', '10-12', 'kindness-character', 200),
('I make time for the people who matter.', '10-12', 'friendship', 201),
('I am grateful for the food on my table.', '10-12', 'gratitude', 202),
('I take notes on life, not just in class.', '10-12', 'curiosity', 203),
('My family believes in me, and I borrow that belief.', '10-12', 'belonging', 204),
('I help the new kid feel welcome at school.', '10-12', 'teamwork', 205),
('Arguing doesn''t mean we stopped loving each other.', '10-12', 'sibling-love', 206),
('I keep my word, even when it''s inconvenient.', '10-12', 'responsibility', 207),
('It''s fine to not know the answer yet.', '10-12', 'confidence', 208),
('I am on my own timeline.', '10-12', 'self-worth', 209),
('I can speak for myself.', '10-12', 'independence', 210),
('I don''t let one bad grade define me.', '10-12', 'resilience', 211),
('I let the wave pass instead of fighting it.', '10-12', 'emotional-calm', 212),
('I own my mistakes instead of blaming others.', '10-12', 'kindness-character', 213),
('I can say "that hurt" instead of going silent.', '10-12', 'friendship', 214),
('Saying thank you makes me feel good too.', '10-12', 'gratitude', 215),
('I am curious about people, not just topics.', '10-12', 'curiosity', 216),
('I don''t have to face hard things alone.', '10-12', 'belonging', 217),
('Doing my homework is my part of the deal.', '10-12', 'teamwork', 218),
('I am proud of who my sister is becoming.', '10-12', 'sibling-love', 219),
('I put in the work before I expect the result.', '10-12', 'responsibility', 220),
('Showing up counts, and I notice when I do.', '10-12', 'confidence', 221),
('I like my own company.', '10-12', 'self-worth', 222),
('I take responsibility for my part.', '10-12', 'independence', 223),
('Losing a game doesn''t make me a loser.', '10-12', 'resilience', 224),
('I am allowed to have an off day.', '10-12', 'emotional-calm', 225),
('I give people the benefit of the doubt.', '10-12', 'kindness-character', 226),
('I respect when a friend needs space.', '10-12', 'friendship', 227),
('I look for one good thing every single day.', '10-12', 'gratitude', 228),
('I don''t give up when something is confusing at first.', '10-12', 'curiosity', 229),
('Love in my house isn''t earned; it''s just there.', '10-12', 'belonging', 230),
('I say thank you when someone helps me.', '10-12', 'teamwork', 231),
('We look out for each other when parents aren''t around.', '10-12', 'sibling-love', 232),
('My room, my mess, my job.', '10-12', 'responsibility', 233),
('I can be quiet and still be strong.', '10-12', 'confidence', 234),
('I don''t need everyone to like me.', '10-12', 'self-worth', 235),
('I can try a new route and find my own way.', '10-12', 'independence', 236),
('I can sit with discomfort and come out fine.', '10-12', 'resilience', 237),
('Counting to ten actually works, and I use it.', '10-12', 'emotional-calm', 238),
('Small kindnesses add up, and I do them.', '10-12', 'kindness-character', 239),
('I keep my friends'' private things private.', '10-12', 'friendship', 240),
('I am thankful for friends who make me laugh.', '10-12', 'gratitude', 241),
('I look things up instead of just guessing.', '10-12', 'curiosity', 242),
('Someone is always glad I came home.', '10-12', 'belonging', 243),
('A good team talks things out. I use my words.', '10-12', 'teamwork', 244),
('I can be patient with my younger sibling.', '10-12', 'sibling-love', 245),
('I ask for help when I need it, then I finish the job.', '10-12', 'responsibility', 246),
('What I think about me matters more than what they think.', '10-12', 'confidence', 247),
('It''s okay to outgrow things that don''t fit anymore.', '10-12', 'self-worth', 248),
('I don''t need constant check-ins to stay on track.', '10-12', 'independence', 249),
('I rebuild. I always rebuild.', '10-12', 'resilience', 250),
('I don''t make big decisions when I''m upset.', '10-12', 'emotional-calm', 251),
('I don''t need a reason to be decent.', '10-12', 'kindness-character', 252),
('Making one new friend is a win.', '10-12', 'friendship', 253),
('I appreciate teachers who actually try.', '10-12', 'gratitude', 254),
('I learn from people who disagree with me.', '10-12', 'curiosity', 255),
('I fit in my family like a piece that was made for it.', '10-12', 'belonging', 256),
('I share what I know when a friend is stuck.', '10-12', 'teamwork', 257),
('My brother pushes me to be better.', '10-12', 'sibling-love', 258),
('Excuses don''t get things done. I do.', '10-12', 'responsibility', 259),
('I am allowed to be proud of myself.', '10-12', 'confidence', 260),
('I am worth the effort it takes to grow.', '10-12', 'self-worth', 261),
('I can get myself ready without being chased.', '10-12', 'independence', 262),
('Pain now doesn''t mean pain forever.', '10-12', 'resilience', 263),
('It''s fine to say "I''m not okay right now."', '10-12', 'emotional-calm', 264),
('I stand by my friends, especially when it''s unpopular.', '10-12', 'kindness-character', 265),
('I am patient with people who are different from me.', '10-12', 'friendship', 266),
('I am grateful I get to learn new things.', '10-12', 'gratitude', 267),
('Every expert was once a beginner, including me.', '10-12', 'curiosity', 268),
('I am held, even when I push away.', '10-12', 'belonging', 269),
('Family first means I show up for them.', '10-12', 'teamwork', 270),
('One day we''ll laugh about the fights we have now.', '10-12', 'sibling-love', 271),
('I treat my commitments like they matter, because they do.', '10-12', 'responsibility', 272),
('I don''t have to earn the right to try.', '10-12', 'confidence', 273),
('Nobody gets to decide who I am but me.', '10-12', 'self-worth', 274),
('I learn from my own mistakes, not just other people''s warnings.', '10-12', 'independence', 275),
('Tears don''t stop me for long.', '10-12', 'resilience', 276),
('I treat my bad moods like weather: they pass.', '10-12', 'emotional-calm', 277),
('I am fair, even when I could get away with more.', '10-12', 'kindness-character', 278),
('I laugh with people, not at them.', '10-12', 'friendship', 279),
('I try to complain less and notice more.', '10-12', 'gratitude', 280),
('I practice until it clicks.', '10-12', 'curiosity', 281),
('My family sees the real me and stays.', '10-12', 'belonging', 282),
('I can walk into a room like I belong there.', '10-12', 'confidence', 283),
('I forgive myself for yesterday.', '10-12', 'self-worth', 284),
('I can say no when I need to.', '10-12', 'independence', 285),
('Being told no just means not this way.', '10-12', 'resilience', 286),
('I can be frustrated without taking it out on people.', '10-12', 'emotional-calm', 287),
('I listen before I judge.', '10-12', 'kindness-character', 288),
('I can be the one who says hi first.', '10-12', 'friendship', 289),
('I am thankful for mornings I get to start fresh.', '10-12', 'gratitude', 290),
('I am allowed to be interested in weird things.', '10-12', 'curiosity', 291),
('I belong to people who want the best for me.', '10-12', 'belonging', 292),
('Saying "I don''t know" takes guts, and I have them.', '10-12', 'confidence', 293),
('I am allowed to want good things for myself.', '10-12', 'self-worth', 294),
('I trust my own judgment.', '10-12', 'independence', 295),
('I keep my head up when things go sideways.', '10-12', 'resilience', 296),
('Quiet time is not wasted time.', '10-12', 'emotional-calm', 297),
('I leave people better than I found them.', '10-12', 'kindness-character', 298),
('I don''t need to be the center of the group.', '10-12', 'friendship', 299),
('I appreciate the quiet moments, not just the exciting ones.', '10-12', 'gratitude', 300),
('I connect what I learn to real life.', '10-12', 'curiosity', 301),
('Home is my reset button.', '10-12', 'belonging', 302),
('I decide what kind of day I''m going to have.', '10-12', 'confidence', 303),
('I don''t shrink myself to make others comfortable.', '10-12', 'self-worth', 304),
('I can do hard things without an audience.', '10-12', 'independence', 305),
('I have made it through 100% of my hardest days.', '10-12', 'resilience', 306),
('I check in with myself the way I''d check on a friend.', '10-12', 'emotional-calm', 307),
('Doing the right thing is its own reward.', '10-12', 'kindness-character', 308),
('I forgive my friends when they mess up.', '10-12', 'friendship', 309),
('I am grateful for my health today.', '10-12', 'gratitude', 310),
('I don''t rush past the interesting parts.', '10-12', 'curiosity', 311),
('I am never too much for the people who love me.', '10-12', 'belonging', 312),
('I can disagree without being mean about it.', '10-12', 'confidence', 313),
('I matter, even on the days I feel invisible.', '10-12', 'self-worth', 314),
('I clean up my own messes.', '10-12', 'independence', 315),
('I don''t need everything to go right to be okay.', '10-12', 'resilience', 316),
('I don''t have to explain my feelings to deserve them.', '10-12', 'emotional-calm', 317),
('I don''t tear others down to feel taller.', '10-12', 'kindness-character', 318),
('I choose friends who bring out my best.', '10-12', 'friendship', 319),
('I thank my family, even when they annoy me.', '10-12', 'gratitude', 320),
('My brain grows when I use it.', '10-12', 'curiosity', 321),
('My family''s love doesn''t run out.', '10-12', 'belonging', 322),
('I am more capable than I give myself credit for.', '10-12', 'confidence', 323),
('I am proud of how far I''ve already come.', '10-12', 'self-worth', 324),
('I am becoming someone I can count on.', '10-12', 'independence', 325),
('I am still here, and that counts for a lot.', '10-12', 'resilience', 326),
('I can find my calm again. I always do.', '10-12', 'emotional-calm', 327),
('The kind of person I am matters more than what I achieve.', '10-12', 'kindness-character', 328),
('A good friend is someone I am becoming, too.', '10-12', 'friendship', 329),
('There is always something. I look for it.', '10-12', 'gratitude', 330),
('I stay curious even when the answer is hard.', '10-12', 'curiosity', 331),
('I carry my family with me wherever I go.', '10-12', 'belonging', 332);
