insert into public.affirmations (text, age_band, pillar, sort_order) values
('I trust myself to figure things out.', '13+', 'confidence', 0),
('I am enough, exactly as I am right now.', '13+', 'self-worth', 1),
('I can handle this on my own.', '13+', 'independence', 2),
('I get back up. Every time.', '13+', 'resilience', 3),
('My feelings are valid, even the uncomfortable ones.', '13+', 'emotional-calm', 4),
('The kind of person I am matters more than what I achieve.', '13+', 'kindness-character', 5),
('I can start a conversation with someone new.', '13+', 'friendship', 6),
('I notice the good, even on ordinary days.', '13+', 'gratitude', 7),
('I wonder about things, and that''s a strength.', '13+', 'curiosity', 8),
('I am loved, even when I mess up.', '13+', 'belonging', 9),
('I don''t have to do everything. I have to do my part.', '13+', 'teamwork', 10),
('One day my siblings will be my oldest friends.', '13+', 'sibling-love', 11),
('Discipline is doing what needs doing even when I don''t feel like it.', '13+', 'responsibility', 12),
('My voice matters even when it shakes.', '13+', 'confidence', 13),
('My value isn''t measured in likes or grades.', '13+', 'self-worth', 14),
('I figure things out instead of waiting to be rescued.', '13+', 'independence', 15),
('A bad day is not a bad life.', '13+', 'resilience', 16),
('I can feel angry without acting angry.', '13+', 'emotional-calm', 17),
('I treat people the way I want to be remembered.', '13+', 'kindness-character', 18),
('I listen more than I talk.', '13+', 'friendship', 19),
('I am thankful for people who show up for me.', '13+', 'gratitude', 20),
('Questions make me smarter than answers do.', '13+', 'curiosity', 21),
('My family is my team — we win and lose together.', '13+', 'belonging', 22),
('Asking for help is not weakness. It is how teams work.', '13+', 'teamwork', 23),
('I don''t have to like my brother to love him — but I do both.', '13+', 'sibling-love', 24),
('I handle my responsibilities before I chase my wants.', '13+', 'responsibility', 25),
('I don''t need permission to start.', '13+', 'confidence', 26),
('I don''t have to earn the right to take up space.', '13+', 'self-worth', 27),
('I make my own decisions and stand by them.', '13+', 'independence', 28),
('I have survived every hard thing so far — that''s a perfect record.', '13+', 'resilience', 29),
('This emotion will pass — all of them do.', '13+', 'emotional-calm', 30),
('Being kind costs me nothing and means everything.', '13+', 'kindness-character', 31),
('Good friends are made by being a good friend first.', '13+', 'friendship', 32),
('I have more than I give myself credit for.', '13+', 'gratitude', 33),
('I love learning things nobody assigned me.', '13+', 'curiosity', 34),
('I belong here exactly as I am.', '13+', 'belonging', 35),
('I pull my weight at home without being asked twice.', '13+', 'teamwork', 36),
('My sister is the only person who remembers my whole childhood.', '13+', 'sibling-love', 37),
('Nobody''s coming to do it for me, and that''s fine. I can handle it.', '13+', 'responsibility', 38),
('Trying is already a kind of courage.', '13+', 'confidence', 39),
('I am not a project to be fixed.', '13+', 'self-worth', 40),
('I don''t need someone else to tell me what to do.', '13+', 'independence', 41),
('Failure is information, not identity.', '13+', 'resilience', 42),
('I don''t have to fix my feelings; I just have to feel them.', '13+', 'emotional-calm', 43),
('I do the right thing even when no one is watching.', '13+', 'kindness-character', 44),
('I don''t need a huge circle — a few real ones is enough.', '13+', 'friendship', 45),
('Gratitude turns what I have into enough.', '13+', 'gratitude', 46),
('Being wrong is how I get righter.', '13+', 'curiosity', 47),
('Home is people, not a place — and I have people.', '13+', 'belonging', 48),
('My siblings and I are on the same side, even when we fight.', '13+', 'teamwork', 49),
('I show up for my siblings even when it''s inconvenient.', '13+', 'sibling-love', 50),
('My word means something because I back it up.', '13+', 'responsibility', 51),
('I can speak up without apologizing for existing.', '13+', 'confidence', 52),
('Who I am matters more than what I produce.', '13+', 'self-worth', 53),
('I take responsibility for my own life.', '13+', 'independence', 54),
('I bend without breaking.', '13+', 'resilience', 55),
('I breathe, and the storm gets smaller.', '13+', 'emotional-calm', 56),
('I stand up for people who can''t stand up for themselves.', '13+', 'kindness-character', 57),
('I can join a group without waiting for an invitation.', '13+', 'friendship', 58),
('I appreciate the small things — they add up.', '13+', 'gratitude', 59),
('I read, watch, and ask — I feed my mind.', '13+', 'curiosity', 60),
('I don''t have to earn my family''s love.', '13+', 'belonging', 61),
('I listen to understand, not just to reply.', '13+', 'teamwork', 62),
('I respect my brother''s choices even when I''d choose differently.', '13+', 'sibling-love', 63),
('I do the unglamorous work without needing applause.', '13+', 'responsibility', 64),
('What I think is worth saying out loud.', '13+', 'confidence', 65),
('I deserve the same kindness I give others.', '13+', 'self-worth', 66),
('I can solve problems without panicking.', '13+', 'independence', 67),
('What knocked me down taught me something.', '13+', 'resilience', 68),
('It''s okay to not be okay for a while.', '13+', 'emotional-calm', 69),
('My character is what I do when it''s inconvenient.', '13+', 'kindness-character', 70),
('I remember small things about people, and it matters to them.', '13+', 'friendship', 71),
('I say thank you and mean it.', '13+', 'gratitude', 72),
('I don''t have to know everything to start learning something.', '13+', 'curiosity', 73),
('I am part of something bigger than myself.', '13+', 'belonging', 74),
('Credit shared is credit doubled. I don''t need to be the hero.', '13+', 'teamwork', 75),
('I can be honest with my sister without being harsh.', '13+', 'sibling-love', 76),
('Being reliable is a reputation I build one kept promise at a time.', '13+', 'responsibility', 77),
('I give myself the same chance I''d give a friend.', '13+', 'confidence', 78),
('I can like myself without being arrogant.', '13+', 'self-worth', 79),
('Asking for help is a choice, not a failure of independence.', '13+', 'independence', 80),
('I can start again without shame.', '13+', 'resilience', 81),
('I name what I feel, and it loses some power over me.', '13+', 'emotional-calm', 82),
('I apologize when I''m wrong — quickly and sincerely.', '13+', 'kindness-character', 83),
('I am easy to be around because I pay attention.', '13+', 'friendship', 84),
('Someone, somewhere, made my life easier today.', '13+', 'gratitude', 85),
('Curiosity got me further than fear ever did.', '13+', 'curiosity', 86),
('My family wants me to succeed, not to be perfect.', '13+', 'belonging', 87),
('Doing the boring job well is what makes me reliable.', '13+', 'teamwork', 88),
('Nobody can tease my sister except me.', '13+', 'sibling-love', 89),
('I take care of my space, my work, and my people.', '13+', 'responsibility', 90),
('Being nervous doesn''t mean I''m not ready.', '13+', 'confidence', 91),
('My worth doesn''t drop when I make a mistake.', '13+', 'self-worth', 92),
('I manage my own time like it belongs to me — because it does.', '13+', 'independence', 93),
('Tough seasons don''t last, but tough people adapt.', '13+', 'resilience', 94),
('I can pause before I react.', '13+', 'emotional-calm', 95),
('I don''t gossip; I don''t need to tear others down to feel tall.', '13+', 'kindness-character', 96),
('I can disagree with a friend and still keep the friendship.', '13+', 'friendship', 97),
('I don''t take the people I love for granted.', '13+', 'gratitude', 98),
('I learn from people who disagree with me.', '13+', 'curiosity', 99),
('I can come home — always.', '13+', 'belonging', 100),
('I respect people who do the work nobody sees.', '13+', 'teamwork', 101),
('I want my siblings to know I''m proud of them.', '13+', 'sibling-love', 102),
('I''d rather be tired from effort than restless from avoidance.', '13+', 'responsibility', 103),
('I stop rehearsing and just begin.', '13+', 'confidence', 104),
('I don''t need to prove myself to be valuable.', '13+', 'self-worth', 105),
('I learn by doing, not by being shown every step.', '13+', 'independence', 106),
('I am allowed to fall apart and still put myself back together.', '13+', 'resilience', 107),
('Sadness is not weakness; it''s honesty.', '13+', 'emotional-calm', 108),
('Honesty is my default, even when it''s uncomfortable.', '13+', 'kindness-character', 109),
('I check on my friends, not just when I need something.', '13+', 'friendship', 110),
('I am grateful for my health, whatever shape it''s in.', '13+', 'gratitude', 111),
('I try new things even if I might be bad at them.', '13+', 'curiosity', 112),
('Being known deeply by my family is a gift.', '13+', 'belonging', 113),
('Family is a team sport. I show up for practice.', '13+', 'teamwork', 114),
('The bond with my siblings outlasts every argument.', '13+', 'sibling-love', 115),
('I finish things. That''s what separates intentions from results.', '13+', 'responsibility', 116),
('My ideas don''t have to be perfect to matter.', '13+', 'confidence', 117),
('I am more than my worst moment.', '13+', 'self-worth', 118),
('I can be alone without feeling lonely.', '13+', 'independence', 119),
('Rejection redirects me; it doesn''t define me.', '13+', 'resilience', 120),
('I give myself permission to have a bad day.', '13+', 'emotional-calm', 121),
('I help without keeping score.', '13+', 'kindness-character', 122),
('It''s okay to outgrow friendships that no longer fit.', '13+', 'friendship', 123),
('Even hard days have one good moment — I look for it.', '13+', 'gratitude', 124),
('I am a beginner at many things, and that''s exciting.', '13+', 'curiosity', 125),
('I add something to my family that no one else can.', '13+', 'belonging', 126),
('I can be right without making someone else feel small.', '13+', 'teamwork', 127),
('I check on my sister for no reason.', '13+', 'sibling-love', 128),
('Owning my mistakes is part of owning my life.', '13+', 'responsibility', 129),
('I can ask for what I need.', '13+', 'confidence', 130),
('I respect myself enough to say no.', '13+', 'self-worth', 131),
('My choices are mine, and I own the results.', '13+', 'independence', 132),
('I keep going when it''s boring, not just when it''s exciting.', '13+', 'resilience', 133),
('I don''t have to earn rest by being productive first.', '13+', 'emotional-calm', 134),
('I am the same person in every room.', '13+', 'kindness-character', 135),
('I make people feel heard.', '13+', 'friendship', 136),
('I thank people specifically, not generically.', '13+', 'gratitude', 137),
('I ask "why" without embarrassment.', '13+', 'curiosity', 138),
('I am rooted, even when I roam.', '13+', 'belonging', 139),
('When the group struggles, I step in instead of stepping back.', '13+', 'teamwork', 140),
('My siblings knew me before I knew myself.', '13+', 'sibling-love', 141),
('I don''t need motivation to start. I start, and motivation follows.', '13+', 'responsibility', 142),
('Confidence is built, not born — and I''m building it.', '13+', 'confidence', 143),
('Being different from the crowd isn''t a flaw.', '13+', 'self-worth', 144),
('I don''t follow the crowd just to feel safe.', '13+', 'independence', 145),
('My scars are proof I kept trying.', '13+', 'resilience', 146),
('My nervous system is not my enemy.', '13+', 'emotional-calm', 147),
('I give people the benefit of the doubt first.', '13+', 'kindness-character', 148),
('I don''t have to be the funniest person in the room to belong.', '13+', 'friendship', 149),
('I am lucky in ways I forget to count.', '13+', 'gratitude', 150),
('I learn something new every week on purpose.', '13+', 'curiosity', 151),
('My family''s story includes me, and I''m proud of that.', '13+', 'belonging', 152),
('I keep my promises to my friends.', '13+', 'teamwork', 153),
('I forgive the dumb stuff we did as kids.', '13+', 'sibling-love', 154),
('The standard I hold is mine, and I don''t lower it when no one''s watching.', '13+', 'responsibility', 155),
('I refuse to shrink myself to make others comfortable.', '13+', 'confidence', 156),
('I am allowed to take care of myself first sometimes.', '13+', 'self-worth', 157),
('I can cook, clean, plan, and handle my business.', '13+', 'independence', 158),
('I don''t quit on myself.', '13+', 'resilience', 159),
('I can calm myself down — I have done it before.', '13+', 'emotional-calm', 160),
('Respect isn''t earned by titles — I give it freely.', '13+', 'kindness-character', 161),
('I reach out first sometimes.', '13+', 'friendship', 162),
('A roof, food, people who care — that''s a lot.', '13+', 'gratitude', 163),
('My brain grows when I challenge it.', '13+', 'curiosity', 164),
('I don''t have to face hard things alone.', '13+', 'belonging', 165),
('Tolerance means giving people room to be different from me.', '13+', 'teamwork', 166),
('Being a good sibling is a choice I make daily.', '13+', 'sibling-love', 167),
('I do my part without keeping score.', '13+', 'responsibility', 168),
('I can handle being seen.', '13+', 'confidence', 169);
insert into public.affirmations (text, age_band, pillar, sort_order) values
('My body is not a problem to solve.', '13+', 'self-worth', 170),
('I think for myself before I check what others think.', '13+', 'independence', 171),
('Hard things make me stronger only if I let them — and I choose to.', '13+', 'resilience', 172),
('I don''t let a feeling make my decisions for me.', '13+', 'emotional-calm', 173),
('I clean up my own messes, literal and otherwise.', '13+', 'kindness-character', 174),
('I respect other people''s boundaries the way I want mine respected.', '13+', 'friendship', 175),
('I appreciate what my parents do, even when we disagree.', '13+', 'gratitude', 176),
('I don''t memorize — I understand.', '13+', 'curiosity', 177),
('Love in my family isn''t conditional on achievement.', '13+', 'belonging', 178),
('I do my homework because my education is my job right now.', '13+', 'teamwork', 179),
('I don''t take my sister for granted.', '13+', 'sibling-love', 180),
('Homework, chores, commitments — I handle what''s mine.', '13+', 'responsibility', 181),
('Doubt can ride along, but it doesn''t get to drive.', '13+', 'confidence', 182),
('I don''t compare my behind-the-scenes to someone else''s highlight reel.', '13+', 'self-worth', 183),
('I am becoming someone I can rely on.', '13+', 'independence', 184),
('I can sit with discomfort without running from it.', '13+', 'resilience', 185),
('It''s fine to cry. It doesn''t undo my strength.', '13+', 'emotional-calm', 186),
('I keep my promises, especially the small ones.', '13+', 'kindness-character', 187),
('I can be myself around the right people.', '13+', 'friendship', 188),
('I notice beauty without needing to photograph it.', '13+', 'gratitude', 189),
('I explore ideas the way others explore places.', '13+', 'curiosity', 190),
('I belong to people who would drop everything for me.', '13+', 'belonging', 191),
('Chores are not punishment. They are my share of the house.', '13+', 'teamwork', 192),
('We don''t talk every day, but I''d drop everything for them.', '13+', 'sibling-love', 193),
('I prepare today so tomorrow isn''t a scramble.', '13+', 'responsibility', 194),
('I choose to show up instead of hiding.', '13+', 'confidence', 195),
('I am worthy of good things, not just hard things.', '13+', 'self-worth', 196),
('I don''t wait for the perfect moment — I make a plan and go.', '13+', 'independence', 197),
('A setback is just a plot twist, not the ending.', '13+', 'resilience', 198),
('I check in with myself the way I''d check on a friend.', '13+', 'emotional-calm', 199),
('I choose patience over being right in an argument.', '13+', 'kindness-character', 200),
('Loneliness is temporary; connection takes effort, and I put it in.', '13+', 'friendship', 201),
('I am thankful for second chances.', '13+', 'gratitude', 202),
('I am allowed to change my mind when I learn more.', '13+', 'curiosity', 203),
('I carry my family''s strength with me wherever I go.', '13+', 'belonging', 204),
('I celebrate my friends'' wins like they are mine.', '13+', 'teamwork', 205),
('My brother''s success doesn''t take away from mine.', '13+', 'sibling-love', 206),
('Doing my best is a habit, not a mood.', '13+', 'responsibility', 207),
('My opinion is allowed to take up space.', '13+', 'confidence', 208),
('I can be proud of myself quietly.', '13+', 'self-worth', 209),
('I can navigate unfamiliar places and situations.', '13+', 'independence', 210),
('I recover at my own pace, and that''s fine.', '13+', 'resilience', 211),
('Anxiety is a signal, not a sentence.', '13+', 'emotional-calm', 212),
('I don''t laugh at jokes that punch down.', '13+', 'kindness-character', 213),
('I celebrate my friends'' wins like they''re my own.', '13+', 'friendship', 214),
('Gratitude is my reset button.', '13+', 'gratitude', 215),
('I seek out perspectives different from mine.', '13+', 'curiosity', 216),
('I am accepted here — the real me, not the polished version.', '13+', 'belonging', 217),
('A team is only as strong as its weakest moment. I don''t quit on mine.', '13+', 'teamwork', 218),
('I tell my siblings I love them, even if it''s awkward.', '13+', 'sibling-love', 219),
('I take pride in being someone others can lean on.', '13+', 'responsibility', 220),
('I don''t need everyone to agree with me.', '13+', 'confidence', 221),
('I don''t need a reason to deserve rest.', '13+', 'self-worth', 222),
('I take care of my own responsibilities without being asked.', '13+', 'independence', 223),
('I don''t have to be okay right now to be okay eventually.', '13+', 'resilience', 224),
('I can hold two feelings at once and still be fine.', '13+', 'emotional-calm', 225),
('I make room for people who are different from me.', '13+', 'kindness-character', 226),
('I don''t compete with my friends — I grow with them.', '13+', 'friendship', 227),
('I don''t need more to be happy right now.', '13+', 'gratitude', 228),
('Learning is not just for school — it''s for life.', '13+', 'curiosity', 229),
('My family sees me trying, and that counts.', '13+', 'belonging', 230),
('I apologize when I am wrong, even when it is uncomfortable.', '13+', 'teamwork', 231),
('Growing up, my siblings were my first real friends.', '13+', 'sibling-love', 232),
('If it''s my job, it''s done right. No shortcuts.', '13+', 'responsibility', 233),
('I can do hard things while scared.', '13+', 'confidence', 234),
('I am not "too much" — I am exactly right for the right people.', '13+', 'self-worth', 235),
('Independence means I get to choose my direction.', '13+', 'independence', 236),
('Pain passes. I remain.', '13+', 'resilience', 237),
('I slow down when everything feels too fast.', '13+', 'emotional-calm', 238),
('Integrity means my words and actions match.', '13+', 'kindness-character', 239),
('I can handle small talk; it often leads somewhere real.', '13+', 'friendship', 240),
('I appreciate my own effort, not just results.', '13+', 'gratitude', 241),
('I pay attention; the world is interesting if I look.', '13+', 'curiosity', 242),
('I have a seat at this table, no matter what.', '13+', 'belonging', 243),
('I make room for the quiet kid. Everyone deserves a seat.', '13+', 'teamwork', 244),
('I protect my little sister without making her feel small.', '13+', 'sibling-love', 245),
('I respect my own time by not wasting it.', '13+', 'responsibility', 246),
('I give myself credit for how far I''ve come.', '13+', 'confidence', 247),
('My existence doesn''t require justification.', '13+', 'self-worth', 248),
('I learn from my own mistakes instead of fearing them.', '13+', 'independence', 249),
('I learn the lesson and leave the regret.', '13+', 'resilience', 250),
('I don''t have to smile through everything.', '13+', 'emotional-calm', 251),
('I am kind to strangers and rivals alike.', '13+', 'kindness-character', 252),
('I am loyal without losing myself.', '13+', 'friendship', 253),
('I am grateful for the friends who stayed.', '13+', 'gratitude', 254),
('I take things apart to see how they work.', '13+', 'curiosity', 255),
('We look out for each other — that''s what we do.', '13+', 'belonging', 256),
('Leadership is serving the team, not bossing it.', '13+', 'teamwork', 257),
('Family is the team I never get traded from.', '13+', 'sibling-love', 258),
('Responsibility isn''t a burden. It''s proof I''m growing up.', '13+', 'responsibility', 259),
('I am capable of more than my worst day suggested.', '13+', 'confidence', 260),
('I treat myself like someone I''m responsible for.', '13+', 'self-worth', 261),
('I can stand alone when my values require it.', '13+', 'independence', 262),
('I am harder to break than I look.', '13+', 'resilience', 263),
('Peace is something I can practice.', '13+', 'emotional-calm', 264),
('I tell the truth even when a lie would be easier.', '13+', 'kindness-character', 265),
('I give compliments freely and mean them.', '13+', 'friendship', 266),
('Today I choose to focus on what went right.', '13+', 'gratitude', 267),
('I am curious about people, not just topics.', '13+', 'curiosity', 268),
('I am someone''s favorite person to come home to.', '13+', 'belonging', 269),
('At the end of the day, I want people to say I was solid.', '13+', 'teamwork', 270),
('I hope my siblings know they can always call me.', '13+', 'sibling-love', 271),
('I earn trust by doing what I said I''d do.', '13+', 'responsibility', 272),
('I walk into rooms like I belong there.', '13+', 'confidence', 273),
('I am allowed to outgrow people who make me feel small.', '13+', 'self-worth', 274),
('I build my own life one decision at a time.', '13+', 'independence', 275),
('When plans fall apart, I make new ones.', '13+', 'resilience', 276),
('I let go of what I can''t control — starting today.', '13+', 'emotional-calm', 277),
('I forgive people — mostly for my own peace.', '13+', 'kindness-character', 278),
('I can eat alone and be perfectly fine — and still enjoy company.', '13+', 'friendship', 279),
('I thank my past self for getting me here.', '13+', 'gratitude', 280),
('I don''t need to be the smartest — I need to stay curious.', '13+', 'curiosity', 281),
('Knowing where I come from helps me know where I''m going.', '13+', 'belonging', 282),
('I can disagree with someone I respect.', '13+', 'confidence', 283),
('What I feel inside counts more than how I look outside.', '13+', 'self-worth', 284),
('I don''t need constant approval to move forward.', '13+', 'independence', 285),
('I can cry about it and still handle it.', '13+', 'resilience', 286),
('My mind can race; I don''t have to chase it.', '13+', 'emotional-calm', 287),
('I leave places better than I found them.', '13+', 'kindness-character', 288),
('I choose friends who make me want to be better.', '13+', 'friendship', 289),
('I notice when someone is kind to me, and I remember it.', '13+', 'gratitude', 290),
('I learn from failure faster than from success.', '13+', 'curiosity', 291),
('I don''t have to be far from home to feel its pull.', '13+', 'belonging', 292),
('My potential isn''t decided by anyone else''s opinion.', '13+', 'confidence', 293),
('I choose people who see my worth clearly.', '13+', 'self-worth', 294),
('I am capable of running my own day.', '13+', 'independence', 295),
('I don''t let one loss decide the whole game.', '13+', 'resilience', 296),
('I am allowed to step away and reset.', '13+', 'emotional-calm', 297),
('I don''t need credit to do good.', '13+', 'kindness-character', 298),
('I don''t chase people who don''t choose me back.', '13+', 'friendship', 299),
('I am grateful I get to try again tomorrow.', '13+', 'gratitude', 300),
('I follow my interests even when they''re unusual.', '13+', 'curiosity', 301),
('I am loved in my worst moments, not just my best.', '13+', 'belonging', 302),
('I start before I feel ready.', '13+', 'confidence', 303),
('I am not behind; I''m on my own timeline.', '13+', 'self-worth', 304),
('I trust my judgment even when it''s unpopular.', '13+', 'independence', 305),
('I have been through worse and came out wiser.', '13+', 'resilience', 306),
('Feelings are visitors, not residents.', '13+', 'emotional-calm', 307),
('I treat my family with the same respect I show my friends.', '13+', 'kindness-character', 308),
('I show up for the people I care about.', '13+', 'friendship', 309),
('Contentment is a skill I practice daily.', '13+', 'gratitude', 310),
('I ask better questions than I did last year.', '13+', 'curiosity', 311),
('Family means I never start from zero.', '13+', 'belonging', 312),
('I am allowed to want big things.', '13+', 'confidence', 313),
('I can love who I''m becoming while accepting who I am.', '13+', 'self-worth', 314),
('I can start over somewhere new and be fine.', '13+', 'independence', 315),
('Giving up is the only real failure, and I don''t do that.', '13+', 'resilience', 316),
('I treat my bad moods with patience, not punishment.', '13+', 'emotional-calm', 317),
('Being a good person is a daily practice, not a title.', '13+', 'kindness-character', 318),
('Vulnerability with the right people builds real closeness.', '13+', 'friendship', 319),
('I appreciate the quiet moments too.', '13+', 'gratitude', 320),
('Knowledge compounds — small learning adds up.', '13+', 'curiosity', 321),
('I bring my whole self home, and it''s welcome.', '13+', 'belonging', 322),
('What I bring to the table is enough.', '13+', 'confidence', 323),
('I matter, even on ordinary days.', '13+', 'self-worth', 324),
('My life is mine to shape.', '13+', 'independence', 325),
('Tomorrow gets a clean slate from me.', '13+', 'resilience', 326),
('Calm is a skill, and I''m getting better at it.', '13+', 'emotional-calm', 327),
('I am someone others can count on.', '13+', 'kindness-character', 328),
('I am a friend worth having.', '13+', 'friendship', 329),
('I end today thankful, whatever it brought.', '13+', 'gratitude', 330),
('I stay teachable, no matter how much I know.', '13+', 'curiosity', 331),
('Wherever I go, I carry belonging with me.', '13+', 'belonging', 332);
