insert into public.affirmations (text, age_band, pillar, sort_order) values
('I can do it.', '4-6', 'confidence', 0),
('I am special.', '4-6', 'self-worth', 1),
('I do it myself.', '4-6', 'independence', 2),
('I can try again.', '4-6', 'resilience', 3),
('I can take a breath.', '4-6', 'emotional-calm', 4),
('I am kind.', '4-6', 'kindness-character', 5),
('I can join in.', '4-6', 'friendship', 6),
('I am thankful.', '4-6', 'gratitude', 7),
('I like to learn.', '4-6', 'curiosity', 8),
('I am loved.', '4-6', 'belonging', 9),
('We help each other.', '4-6', 'teamwork', 10),
('I love my sister.', '4-6', 'sibling-love', 11),
('I do my chores.', '4-6', 'responsibility', 12),
('I can try.', '4-6', 'confidence', 13),
('I am enough.', '4-6', 'self-worth', 14),
('I can zip my coat.', '4-6', 'independence', 15),
('My mistakes are okay.', '4-6', 'resilience', 16),
('I can breathe slow.', '4-6', 'emotional-calm', 17),
('I can share my toys.', '4-6', 'kindness-character', 18),
('I can make friends.', '4-6', 'friendship', 19),
('I am glad for my toys.', '4-6', 'gratitude', 20),
('I can ask questions.', '4-6', 'curiosity', 21),
('My family loves me.', '4-6', 'belonging', 22),
('I share my toys.', '4-6', 'teamwork', 23),
('I love my brother.', '4-6', 'sibling-love', 24),
('I clean my room.', '4-6', 'responsibility', 25),
('I am brave.', '4-6', 'confidence', 26),
('I am good.', '4-6', 'self-worth', 27),
('I can put shoes on.', '4-6', 'independence', 28),
('I can start over.', '4-6', 'resilience', 29),
('I feel my feelings.', '4-6', 'emotional-calm', 30),
('I can say sorry.', '4-6', 'kindness-character', 31),
('I can say hello.', '4-6', 'friendship', 32),
('I love my family.', '4-6', 'gratitude', 33),
('I wonder why.', '4-6', 'curiosity', 34),
('I belong here.', '4-6', 'belonging', 35),
('We clean up together.', '4-6', 'teamwork', 36),
('My brother is my friend.', '4-6', 'sibling-love', 37),
('I finish my work.', '4-6', 'responsibility', 38),
('I can say it.', '4-6', 'confidence', 39),
('I am me.', '4-6', 'self-worth', 40),
('I can pour my milk.', '4-6', 'independence', 41),
('I fall, I get up.', '4-6', 'resilience', 42),
('My feelings are okay.', '4-6', 'emotional-calm', 43),
('I say please and thanks.', '4-6', 'kindness-character', 44),
('I can play with others.', '4-6', 'friendship', 45),
('I smile at the sun.', '4-6', 'gratitude', 46),
('I love to read.', '4-6', 'curiosity', 47),
('I am safe at home.', '4-6', 'belonging', 48),
('I do my part.', '4-6', 'teamwork', 49),
('I am gentle with my brother.', '4-6', 'sibling-love', 50),
('I keep my promise.', '4-6', 'responsibility', 51),
('I can use my voice.', '4-6', 'confidence', 52),
('I like me.', '4-6', 'self-worth', 53),
('I can brush my teeth.', '4-6', 'independence', 54),
('I keep going.', '4-6', 'resilience', 55),
('It is okay to feel sad.', '4-6', 'emotional-calm', 56),
('I can help at home.', '4-6', 'kindness-character', 57),
('I can start a game.', '4-6', 'friendship', 58),
('I like rainy days.', '4-6', 'gratitude', 59),
('I love story time.', '4-6', 'curiosity', 60),
('My family is my team.', '4-6', 'belonging', 61),
('We are a team.', '4-6', 'teamwork', 62),
('I help my little brother.', '4-6', 'sibling-love', 63),
('I do my best.', '4-6', 'responsibility', 64),
('I can stand tall.', '4-6', 'confidence', 65),
('I am a gift.', '4-6', 'self-worth', 66),
('I can pick my shirt.', '4-6', 'independence', 67),
('I don''t give up.', '4-6', 'resilience', 68),
('It is okay to feel mad.', '4-6', 'emotional-calm', 69),
('I can help my teacher.', '4-6', 'kindness-character', 70),
('I can invite a friend.', '4-6', 'friendship', 71),
('My bed is cozy.', '4-6', 'gratitude', 72),
('I can count high.', '4-6', 'curiosity', 73),
('I am never alone.', '4-6', 'belonging', 74),
('I help my sister.', '4-6', 'teamwork', 75),
('My sister makes me laugh.', '4-6', 'sibling-love', 76),
('I help at home.', '4-6', 'responsibility', 77),
('I can start now.', '4-6', 'confidence', 78),
('I am wonderful.', '4-6', 'self-worth', 79),
('I can carry my bag.', '4-6', 'independence', 80),
('I can fix it.', '4-6', 'resilience', 81),
('I can calm my body.', '4-6', 'emotional-calm', 82),
('I tell the truth.', '4-6', 'kindness-character', 83),
('I can pass the ball.', '4-6', 'friendship', 84),
('My breakfast tastes good.', '4-6', 'gratitude', 85),
('I know my ABCs.', '4-6', 'curiosity', 86),
('Mom loves me.', '4-6', 'belonging', 87),
('I help my brother.', '4-6', 'teamwork', 88),
('I hug my brother.', '4-6', 'sibling-love', 89),
('I put toys away.', '4-6', 'responsibility', 90),
('I can be me.', '4-6', 'confidence', 91),
('I am important.', '4-6', 'self-worth', 92),
('I can open the door.', '4-6', 'independence', 93),
('I dust myself off.', '4-6', 'resilience', 94),
('I can hug my pillow.', '4-6', 'emotional-calm', 95),
('I do what I say.', '4-6', 'kindness-character', 96),
('I have friends.', '4-6', 'friendship', 97),
('I love hugs.', '4-6', 'gratitude', 98),
('I can learn new words.', '4-6', 'curiosity', 99),
('Dad loves me.', '4-6', 'belonging', 100),
('We take turns.', '4-6', 'teamwork', 101),
('I am nice to my sister.', '4-6', 'sibling-love', 102),
('I try hard.', '4-6', 'responsibility', 103),
('I am strong.', '4-6', 'confidence', 104),
('I am just right.', '4-6', 'self-worth', 105),
('I can wash my hands.', '4-6', 'independence', 106),
('I am still learning.', '4-6', 'resilience', 107),
('I can sit still.', '4-6', 'emotional-calm', 108),
('I am gentle.', '4-6', 'kindness-character', 109),
('I am fun to play with.', '4-6', 'friendship', 110),
('My books are fun.', '4-6', 'gratitude', 111),
('I like to draw.', '4-6', 'curiosity', 112),
('I get lots of hugs.', '4-6', 'belonging', 113),
('I can share.', '4-6', 'teamwork', 114),
('My siblings are the best.', '4-6', 'sibling-love', 115),
('I do it myself.', '4-6', 'responsibility', 116),
('I can ask why.', '4-6', 'confidence', 117),
('I am great as me.', '4-6', 'self-worth', 118),
('I can clean up toys.', '4-6', 'independence', 119),
('I get a new day.', '4-6', 'resilience', 120),
('I can close my eyes.', '4-6', 'emotional-calm', 121),
('I use kind words.', '4-6', 'kindness-character', 122),
('I can laugh with friends.', '4-6', 'friendship', 123),
('I am thankful for mom.', '4-6', 'gratitude', 124),
('I build tall towers.', '4-6', 'curiosity', 125),
('I am part of us.', '4-6', 'belonging', 126),
('We play together.', '4-6', 'teamwork', 127),
('I play with my brother.', '4-6', 'sibling-love', 128),
('I take care of things.', '4-6', 'responsibility', 129),
('I can show them.', '4-6', 'confidence', 130),
('I am funny.', '4-6', 'self-worth', 131),
('I can make my bed.', '4-6', 'independence', 132),
('I can be patient.', '4-6', 'resilience', 133),
('I can count to ten.', '4-6', 'emotional-calm', 134),
('I can take turns.', '4-6', 'kindness-character', 135),
('I can be a good friend.', '4-6', 'friendship', 136),
('I am thankful for dad.', '4-6', 'gratitude', 137),
('I can try new foods.', '4-6', 'curiosity', 138),
('We stick together.', '4-6', 'belonging', 139),
('I help set the table.', '4-6', 'teamwork', 140),
('My sister helps me.', '4-6', 'sibling-love', 141),
('I finish what I start.', '4-6', 'responsibility', 142),
('I can go first.', '4-6', 'confidence', 143),
('I am sweet.', '4-6', 'self-worth', 144),
('I can help set the table.', '4-6', 'independence', 145),
('I can take my time.', '4-6', 'resilience', 146),
('I can hug myself.', '4-6', 'emotional-calm', 147),
('I can give a hug.', '4-6', 'kindness-character', 148),
('I can ask to play.', '4-6', 'friendship', 149),
('I like being home.', '4-6', 'gratitude', 150),
('I can explore outside.', '4-6', 'curiosity', 151),
('My home is cozy.', '4-6', 'belonging', 152),
('We pick up together.', '4-6', 'teamwork', 153),
('I can say sorry to my brother.', '4-6', 'sibling-love', 154),
('I do my part.', '4-6', 'responsibility', 155),
('I can climb high.', '4-6', 'confidence', 156),
('I am a good kid.', '4-6', 'self-worth', 157),
('I can get my cup.', '4-6', 'independence', 158),
('It is okay to cry.', '4-6', 'resilience', 159),
('I can find quiet.', '4-6', 'emotional-calm', 160),
('I can say good morning.', '4-6', 'kindness-character', 161),
('I can share the swing.', '4-6', 'friendship', 162),
('I am glad for my friends.', '4-6', 'gratitude', 163),
('I like little bugs.', '4-6', 'curiosity', 164),
('I am wanted here.', '4-6', 'belonging', 165),
('I listen to friends.', '4-6', 'teamwork', 166),
('My brother keeps me safe.', '4-6', 'sibling-love', 167),
('I am helpful.', '4-6', 'responsibility', 168),
('I can run fast.', '4-6', 'confidence', 169);
insert into public.affirmations (text, age_band, pillar, sort_order) values
('I am proud of me.', '4-6', 'self-worth', 170),
('I can climb the stairs.', '4-6', 'independence', 171),
('I can rest, then try.', '4-6', 'resilience', 172),
('I can rest my head.', '4-6', 'emotional-calm', 173),
('I clean up my mess.', '4-6', 'kindness-character', 174),
('I listen to friends.', '4-6', 'friendship', 175),
('I like today.', '4-6', 'gratitude', 176),
('I can plant a seed.', '4-6', 'curiosity', 177),
('I am welcomed home.', '4-6', 'belonging', 178),
('We work together.', '4-6', 'teamwork', 179),
('My sister sings with me.', '4-6', 'sibling-love', 180),
('I do it right.', '4-6', 'responsibility', 181),
('I can sing out.', '4-6', 'confidence', 182),
('I smile at me.', '4-6', 'self-worth', 183),
('I can buckle my seat.', '4-6', 'independence', 184),
('I am tougher than tough.', '4-6', 'resilience', 185),
('I can be still and breathe.', '4-6', 'emotional-calm', 186),
('I use manners.', '4-6', 'kindness-character', 187),
('I can hold hands.', '4-6', 'friendship', 188),
('I love playtime.', '4-6', 'gratitude', 189),
('I watch clouds go by.', '4-6', 'curiosity', 190),
('I love family time.', '4-6', 'belonging', 191),
('I help my family.', '4-6', 'teamwork', 192),
('I take turns with my sister.', '4-6', 'sibling-love', 193),
('I remember my jobs.', '4-6', 'responsibility', 194),
('I can dance big.', '4-6', 'confidence', 195),
('I am one of a kind.', '4-6', 'self-worth', 196),
('I can pack my backpack.', '4-6', 'independence', 197),
('I can handle it.', '4-6', 'resilience', 198),
('I can name my feeling.', '4-6', 'emotional-calm', 199),
('I can let it go.', '4-6', 'kindness-character', 200),
('I can sit by someone new.', '4-6', 'friendship', 201),
('I dance to music.', '4-6', 'gratitude', 202),
('I can learn to swim.', '4-6', 'curiosity', 203),
('I fit right in.', '4-6', 'belonging', 204),
('I am a helper.', '4-6', 'teamwork', 205),
('My family sticks together.', '4-6', 'sibling-love', 206),
('I work hard.', '4-6', 'responsibility', 207),
('I can make noise.', '4-6', 'confidence', 208),
('I am happy to be me.', '4-6', 'self-worth', 209),
('I can find my socks.', '4-6', 'independence', 210),
('I bounce back.', '4-6', 'resilience', 211),
('I can say I am sad.', '4-6', 'emotional-calm', 212),
('I let everyone play.', '4-6', 'kindness-character', 213),
('I can learn names.', '4-6', 'friendship', 214),
('Animals make me smile.', '4-6', 'gratitude', 215),
('I can learn to ride.', '4-6', 'curiosity', 216),
('They are my people.', '4-6', 'belonging', 217),
('We share our snacks.', '4-6', 'teamwork', 218),
('I comfort my crying sister.', '4-6', 'sibling-love', 219),
('I tidy up.', '4-6', 'responsibility', 220),
('I feel brave.', '4-6', 'confidence', 221),
('I feel good inside.', '4-6', 'self-worth', 222),
('I can wipe the table.', '4-6', 'independence', 223),
('I am not finished.', '4-6', 'resilience', 224),
('I can cry softly.', '4-6', 'emotional-calm', 225),
('I am a good listener.', '4-6', 'kindness-character', 226),
('I can say nice things.', '4-6', 'friendship', 227),
('I like big trees.', '4-6', 'gratitude', 228),
('I can sing new songs.', '4-6', 'curiosity', 229),
('I am their kid.', '4-6', 'belonging', 230),
('I wait my turn.', '4-6', 'teamwork', 231),
('My sister is special.', '4-6', 'sibling-love', 232),
('I do it now.', '4-6', 'responsibility', 233),
('I can say hi.', '4-6', 'confidence', 234),
('I am a star.', '4-6', 'self-worth', 235),
('I can water the plant.', '4-6', 'independence', 236),
('I will get there.', '4-6', 'resilience', 237),
('I can shake it off.', '4-6', 'emotional-calm', 238),
('I can say thank you.', '4-6', 'kindness-character', 239),
('I can play fair.', '4-6', 'friendship', 240),
('I am glad for water.', '4-6', 'gratitude', 241),
('I can do a twirl.', '4-6', 'curiosity', 242),
('They love me lots.', '4-6', 'belonging', 243),
('We build it together.', '4-6', 'teamwork', 244),
('I cheer for my brother.', '4-6', 'sibling-love', 245),
('I am responsible.', '4-6', 'responsibility', 246),
('I can raise my hand.', '4-6', 'confidence', 247),
('I am bright.', '4-6', 'self-worth', 248),
('I can choose my snack.', '4-6', 'independence', 249),
('I can ask for help.', '4-6', 'resilience', 250),
('I can smile again.', '4-6', 'emotional-calm', 251),
('I help without being asked.', '4-6', 'kindness-character', 252),
('I can cheer for friends.', '4-6', 'friendship', 253),
('I am thankful for my hands.', '4-6', 'gratitude', 254),
('I can mix colors.', '4-6', 'curiosity', 255),
('I am cuddled lots.', '4-6', 'belonging', 256),
('I cheer for friends.', '4-6', 'teamwork', 257),
('My brother loves me.', '4-6', 'sibling-love', 258),
('I care for my things.', '4-6', 'responsibility', 259),
('I can choose.', '4-6', 'confidence', 260),
('I am growing well.', '4-6', 'self-worth', 261),
('I can do tricky things.', '4-6', 'independence', 262),
('My big feelings pass.', '4-6', 'resilience', 263),
('I can feel better soon.', '4-6', 'emotional-calm', 264),
('I am fair.', '4-6', 'kindness-character', 265),
('I like playing together.', '4-6', 'friendship', 266),
('I wake up happy.', '4-6', 'gratitude', 267),
('I find out how.', '4-6', 'curiosity', 268),
('I matter to them.', '4-6', 'belonging', 269),
('We do it together.', '4-6', 'teamwork', 270),
('Sisters and brothers are forever.', '4-6', 'sibling-love', 271),
('I do my share.', '4-6', 'responsibility', 272),
('I can march.', '4-6', 'confidence', 273),
('I like my laugh.', '4-6', 'self-worth', 274),
('I can try alone first.', '4-6', 'independence', 275),
('I can breathe and try.', '4-6', 'resilience', 276),
('My heart can slow down.', '4-6', 'emotional-calm', 277),
('I can hug a sad friend.', '4-6', 'kindness-character', 278),
('I can build with friends.', '4-6', 'friendship', 279),
('I am thankful for my teacher.', '4-6', 'gratitude', 280),
('I ask and ask.', '4-6', 'curiosity', 281),
('I am one of them.', '4-6', 'belonging', 282),
('I can jump in.', '4-6', 'confidence', 283),
('My smile is nice.', '4-6', 'self-worth', 284),
('I am a big kid now.', '4-6', 'independence', 285),
('I learn from oops.', '4-6', 'resilience', 286),
('I can listen to birds.', '4-6', 'emotional-calm', 287),
('I do the right thing.', '4-6', 'kindness-character', 288),
('I can color beside you.', '4-6', 'friendship', 289),
('Colors make me happy.', '4-6', 'gratitude', 290),
('I ask why lots.', '4-6', 'curiosity', 291),
('I am home.', '4-6', 'belonging', 292),
('I can play too.', '4-6', 'confidence', 293),
('I am good inside and out.', '4-6', 'self-worth', 294),
('I can snap it shut.', '4-6', 'independence', 295),
('I am growing stronger.', '4-6', 'resilience', 296),
('I can be gentle with me.', '4-6', 'emotional-calm', 297),
('I think of others.', '4-6', 'kindness-character', 298),
('We can dance together.', '4-6', 'friendship', 299),
('My bike goes fast.', '4-6', 'gratitude', 300),
('I can remember things.', '4-6', 'curiosity', 301),
('I live in love.', '4-6', 'belonging', 302),
('I count.', '4-6', 'confidence', 303),
('I am a happy kid.', '4-6', 'self-worth', 304),
('I can hang my coat.', '4-6', 'independence', 305),
('I can do it slowly.', '4-6', 'resilience', 306),
('I can take a break.', '4-6', 'emotional-calm', 307),
('I can make someone smile.', '4-6', 'kindness-character', 308),
('I love to giggle.', '4-6', 'friendship', 309),
('I notice good things.', '4-6', 'gratitude', 310),
('I am getting smarter.', '4-6', 'curiosity', 311),
('I am their sunshine.', '4-6', 'belonging', 312),
('I can shine.', '4-6', 'confidence', 313),
('I love being me.', '4-6', 'self-worth', 314),
('I can turn off the light.', '4-6', 'independence', 315),
('I like going slow.', '4-6', 'resilience', 316),
('I can find my calm.', '4-6', 'emotional-calm', 317),
('I am a good neighbor.', '4-6', 'kindness-character', 318),
('I can say I missed you.', '4-6', 'friendship', 319),
('I am glad I woke up.', '4-6', 'gratitude', 320),
('My brain is growing.', '4-6', 'curiosity', 321),
('I am always welcome.', '4-6', 'belonging', 322),
('I can do hard things.', '4-6', 'confidence', 323),
('I am glad I''m me.', '4-6', 'self-worth', 324),
('I get ready myself.', '4-6', 'independence', 325),
('I never stay down.', '4-6', 'resilience', 326),
('I am safe right now.', '4-6', 'emotional-calm', 327),
('I have a kind heart.', '4-6', 'kindness-character', 328),
('I can be friendly.', '4-6', 'friendship', 329),
('I am lucky to be me.', '4-6', 'gratitude', 330),
('I have fun learning.', '4-6', 'curiosity', 331),
('I am loved no matter what.', '4-6', 'belonging', 332);
