insert into public.affirmations (text, age_band, pillar, sort_order) values
('I am brave enough to try new things.', '7-9', 'confidence', 0),
('I am enough just the way I am.', '7-9', 'self-worth', 1),
('I can figure things out on my own.', '7-9', 'independence', 2),
('Mistakes help me learn.', '7-9', 'resilience', 3),
('All my feelings are okay to feel.', '7-9', 'emotional-calm', 4),
('I treat others the way I want to be treated.', '7-9', 'kindness-character', 5),
('I can make a new friend today.', '7-9', 'friendship', 6),
('I am thankful for my family today.', '7-9', 'gratitude', 7),
('I love learning new things.', '7-9', 'curiosity', 8),
('I am loved no matter what.', '7-9', 'belonging', 9),
('I do my part for the team.', '7-9', 'teamwork', 10),
('I look out for my little brother.', '7-9', 'sibling-love', 11),
('I finish my homework before I play.', '7-9', 'responsibility', 12),
('My voice matters when I speak up.', '7-9', 'confidence', 13),
('I don''t have to be like anyone else.', '7-9', 'self-worth', 14),
('I can get myself ready in the morning.', '7-9', 'independence', 15),
('I can try again tomorrow.', '7-9', 'resilience', 16),
('I can take a deep breath when I''m upset.', '7-9', 'emotional-calm', 17),
('I can share even when it''s hard.', '7-9', 'kindness-character', 18),
('I listen when my friends talk.', '7-9', 'friendship', 19),
('I notice the good things around me.', '7-9', 'gratitude', 20),
('I can ask "why" as many times as I want.', '7-9', 'curiosity', 21),
('My family is my team.', '7-9', 'belonging', 22),
('I help my brother when he needs me.', '7-9', 'teamwork', 23),
('My sister and I make a good team.', '7-9', 'sibling-love', 24),
('I do my chores without being asked.', '7-9', 'responsibility', 25),
('I can raise my hand even if I feel shy.', '7-9', 'confidence', 26),
('I like who I am becoming.', '7-9', 'self-worth', 27),
('Trying by myself helps me grow.', '7-9', 'independence', 28),
('Falling down doesn''t mean staying down.', '7-9', 'resilience', 29),
('It''s okay to feel angry sometimes.', '7-9', 'emotional-calm', 30),
('Kind words make people feel good.', '7-9', 'kindness-character', 31),
('I can invite someone to play with me.', '7-9', 'friendship', 32),
('I am grateful for my warm bed.', '7-9', 'gratitude', 33),
('I wonder about how the world works.', '7-9', 'curiosity', 34),
('I belong right here with my family.', '7-9', 'belonging', 35),
('We finish faster when we work together.', '7-9', 'teamwork', 36),
('I can share my toys with my brother.', '7-9', 'sibling-love', 37),
('I keep my promises, even small ones.', '7-9', 'responsibility', 38),
('Trying is more important than being perfect.', '7-9', 'confidence', 39),
('I am special and so is everyone else.', '7-9', 'self-worth', 40),
('I can solve small problems without help.', '7-9', 'independence', 41),
('I can get through hard days.', '7-9', 'resilience', 42),
('I can calm my body down when I need to.', '7-9', 'emotional-calm', 43),
('I help at home without being asked.', '7-9', 'kindness-character', 44),
('Good friends take turns.', '7-9', 'friendship', 45),
('Saying thank you makes me feel happy.', '7-9', 'gratitude', 46),
('Reading takes me to new places.', '7-9', 'curiosity', 47),
('Home is where I am safe.', '7-9', 'belonging', 48),
('I share what I have.', '7-9', 'teamwork', 49),
('When my sister is sad, I try to help.', '7-9', 'sibling-love', 50),
('I take care of my things.', '7-9', 'responsibility', 51),
('I trust what I think.', '7-9', 'confidence', 52),
('My worth isn''t about grades or scores.', '7-9', 'self-worth', 53),
('I am in charge of my own choices.', '7-9', 'independence', 54),
('When something breaks, I can fix it or start over.', '7-9', 'resilience', 55),
('Feelings come and feelings go.', '7-9', 'emotional-calm', 56),
('I tell the truth even when it''s scary.', '7-9', 'kindness-character', 57),
('I can say hi to someone new.', '7-9', 'friendship', 58),
('I am thankful for food on my table.', '7-9', 'gratitude', 59),
('I can learn from everyone I meet.', '7-9', 'curiosity', 60),
('I am loved even when I make mistakes.', '7-9', 'belonging', 61),
('I listen when my friends talk.', '7-9', 'teamwork', 62),
('I am lucky to have my brother.', '7-9', 'sibling-love', 63),
('I put real effort into my work.', '7-9', 'responsibility', 64),
('I can ask a question when I don''t understand.', '7-9', 'confidence', 65),
('I matter even on my bad days.', '7-9', 'self-worth', 66),
('I can pack my own bag for school.', '7-9', 'independence', 67),
('I don''t quit when it gets tough.', '7-9', 'resilience', 68),
('I can name what I''m feeling.', '7-9', 'emotional-calm', 69),
('I can cheer up someone who is sad.', '7-9', 'kindness-character', 70),
('I share the game and let others choose too.', '7-9', 'friendship', 71),
('I notice when someone helps me.', '7-9', 'gratitude', 72),
('Questions make my brain stronger.', '7-9', 'curiosity', 73),
('My family cheers for me.', '7-9', 'belonging', 74),
('I help with chores without being asked.', '7-9', 'teamwork', 75),
('We fight sometimes, but we always make up.', '7-9', 'sibling-love', 76),
('I clean up my own mess.', '7-9', 'responsibility', 77),
('It''s okay to be the first one to start.', '7-9', 'confidence', 78),
('I don''t need to win to be valuable.', '7-9', 'self-worth', 79),
('When I don''t know, I can find out.', '7-9', 'independence', 80),
('Bad days end, and good days come back.', '7-9', 'resilience', 81),
('When I''m mad, I can use words, not fists.', '7-9', 'emotional-calm', 82),
('I clean up after myself to help my family.', '7-9', 'kindness-character', 83),
('I can ask my friend how they feel.', '7-9', 'friendship', 84),
('I am grateful for my healthy body.', '7-9', 'gratitude', 85),
('I like figuring out how things work.', '7-9', 'curiosity', 86),
('I have a place at the table.', '7-9', 'belonging', 87),
('My family is my team.', '7-9', 'teamwork', 88),
('I like teaching my little sister new things.', '7-9', 'sibling-love', 89),
('I remember what I am supposed to do.', '7-9', 'responsibility', 90),
('I believe I can do hard things.', '7-9', 'confidence', 91),
('I am a good person inside.', '7-9', 'self-worth', 92),
('I can do hard homework by myself first.', '7-9', 'independence', 93),
('I am stronger than my worst day.', '7-9', 'resilience', 94),
('I can sit quietly until I feel better.', '7-9', 'emotional-calm', 95),
('I say please and thank you and mean it.', '7-9', 'kindness-character', 96),
('Playing fair keeps friends close.', '7-9', 'friendship', 97),
('I can find three good things about today.', '7-9', 'gratitude', 98),
('I can try a new hobby this month.', '7-9', 'curiosity', 99),
('I am part of something bigger than me.', '7-9', 'belonging', 100),
('I take turns and I am fair.', '7-9', 'teamwork', 101),
('My brother knows all my secrets.', '7-9', 'sibling-love', 102),
('I finish what I start, even when it''s boring.', '7-9', 'responsibility', 103),
('My ideas are worth sharing.', '7-9', 'confidence', 104),
('It''s okay to be different from my friends.', '7-9', 'self-worth', 105),
('I am responsible for my own stuff.', '7-9', 'independence', 106),
('I can feel sad and still keep going.', '7-9', 'resilience', 107),
('Being scared is normal and it passes.', '7-9', 'emotional-calm', 108),
('I can forgive when someone says sorry.', '7-9', 'kindness-character', 109),
('I can join a game that''s already started.', '7-9', 'friendship', 110),
('I am thankful for my teachers.', '7-9', 'gratitude', 111),
('Mistakes in learning are just steps.', '7-9', 'curiosity', 112),
('My family loves me on good days and bad.', '7-9', 'belonging', 113),
('I cheer for my friends, not just myself.', '7-9', 'teamwork', 114),
('I stand up for my sister.', '7-9', 'sibling-love', 115),
('I help around the house.', '7-9', 'responsibility', 116),
('I can stand tall even when I''m nervous.', '7-9', 'confidence', 117),
('I am proud of who I am.', '7-9', 'self-worth', 118),
('I can make my own breakfast.', '7-9', 'independence', 119),
('Losing a game doesn''t make me a loser.', '7-9', 'resilience', 120),
('I can ask for a hug when I need one.', '7-9', 'emotional-calm', 121),
('I don''t laugh when someone gets hurt.', '7-9', 'kindness-character', 122),
('I keep my friend''s secrets safe.', '7-9', 'friendship', 123),
('I notice the sunshine and the rain.', '7-9', 'gratitude', 124),
('I wonder what I''ll discover today.', '7-9', 'curiosity', 125),
('I belong at my school too.', '7-9', 'belonging', 126),
('I say sorry when I mess up.', '7-9', 'teamwork', 127),
('Having a brother means never being bored.', '7-9', 'sibling-love', 128),
('I do my homework carefully.', '7-9', 'responsibility', 129),
('I don''t need everyone to agree with me.', '7-9', 'confidence', 130),
('I deserve good things too.', '7-9', 'self-worth', 131),
('I don''t need someone to watch me do it right.', '7-9', 'independence', 132),
('I can learn from what went wrong.', '7-9', 'resilience', 133),
('My tears are allowed.', '7-9', 'emotional-calm', 134),
('I can be kind to the new kid at school.', '7-9', 'kindness-character', 135),
('I can laugh with my friends, not at them.', '7-9', 'friendship', 136),
('I am grateful for books and stories.', '7-9', 'gratitude', 137),
('I can read one more chapter.', '7-9', 'curiosity', 138),
('I am never alone in my heart.', '7-9', 'belonging', 139),
('We clean our room together.', '7-9', 'teamwork', 140),
('I can say sorry first, even when it is hard.', '7-9', 'sibling-love', 141),
('I put things back where they belong.', '7-9', 'responsibility', 142),
('Speaking up gets easier each time I do it.', '7-9', 'confidence', 143),
('I don''t have to change to be loved.', '7-9', 'self-worth', 144),
('I can think before I act.', '7-9', 'independence', 145),
('I bend but I don''t break.', '7-9', 'resilience', 146),
('I can count to ten when I''m frustrated.', '7-9', 'emotional-calm', 147),
('I keep my promises.', '7-9', 'kindness-character', 148),
('I am a good friend to have.', '7-9', 'friendship', 149),
('I can thank someone who helped me today.', '7-9', 'gratitude', 150),
('Learning is like building with blocks.', '7-9', 'curiosity', 151),
('My family needs me just as I am.', '7-9', 'belonging', 152),
('I help my sister with her homework.', '7-9', 'teamwork', 153),
('My sister makes the best partner in crime.', '7-9', 'sibling-love', 154),
('I am someone people can count on.', '7-9', 'responsibility', 155),
('I can start even when I feel unsure.', '7-9', 'confidence', 156),
('I am important to my family.', '7-9', 'self-worth', 157),
('My choices are mine to make.', '7-9', 'independence', 158),
('Tomorrow is a fresh start.', '7-9', 'resilience', 159),
('It''s okay to need some alone time.', '7-9', 'emotional-calm', 160),
('I can share my toys with my brother or sister.', '7-9', 'kindness-character', 161),
('I can work well in a team.', '7-9', 'friendship', 162),
('I am thankful for my home.', '7-9', 'gratitude', 163),
('I am curious about people who are different from me.', '7-9', 'curiosity', 164),
('I am held by love every day.', '7-9', 'belonging', 165),
('I ask for help when I need it.', '7-9', 'teamwork', 166),
('My brother counts on me.', '7-9', 'sibling-love', 167),
('I do the hard thing first.', '7-9', 'responsibility', 168),
('I am allowed to take up space.', '7-9', 'confidence', 169);
insert into public.affirmations (text, age_band, pillar, sort_order) values
('What I think of myself counts the most.', '7-9', 'self-worth', 170),
('I can clean up my own mess.', '7-9', 'independence', 171),
('I can handle disappointment.', '7-9', 'resilience', 172),
('I can tell someone how I feel inside.', '7-9', 'emotional-calm', 173),
('Doing the right thing feels good inside.', '7-9', 'kindness-character', 174),
('When we disagree, I can talk it out.', '7-9', 'friendship', 175),
('Small things can make me smile.', '7-9', 'gratitude', 176),
('I can learn a new word every day.', '7-9', 'curiosity', 177),
('We stick together in my family.', '7-9', 'belonging', 178),
('I am patient when others are slow.', '7-9', 'teamwork', 179),
('We laugh at the same silly jokes.', '7-9', 'sibling-love', 180),
('I take pride in a job well done.', '7-9', 'responsibility', 181),
('When I try, I learn something new.', '7-9', 'confidence', 182),
('I am not my mistakes.', '7-9', 'self-worth', 183),
('I can remember what I need to do.', '7-9', 'independence', 184),
('When I fail, I find another way.', '7-9', 'resilience', 185),
('Worrying doesn''t fix anything, breathing helps.', '7-9', 'emotional-calm', 186),
('I can stand up for someone being picked on.', '7-9', 'kindness-character', 187),
('I can cheer for my friend even when I lose.', '7-9', 'friendship', 188),
('I am grateful for my friends.', '7-9', 'gratitude', 189),
('I like when school teaches me something cool.', '7-9', 'curiosity', 190),
('I am my parents'' pride and joy.', '7-9', 'belonging', 191),
('Everyone''s job matters, including mine.', '7-9', 'teamwork', 192),
('Nobody makes me laugh like my brother does.', '7-9', 'sibling-love', 193),
('I don''t quit when it''s tough.', '7-9', 'responsibility', 194),
('I can tell someone what I need.', '7-9', 'confidence', 195),
('I can like myself even when I mess up.', '7-9', 'self-worth', 196),
('I am capable of more than I think.', '7-9', 'independence', 197),
('Hard times don''t last forever.', '7-9', 'resilience', 198),
('I can let go of the mad feeling.', '7-9', 'emotional-calm', 199),
('I say sorry when I hurt someone.', '7-9', 'kindness-character', 200),
('Friends don''t have to agree on everything.', '7-9', 'friendship', 201),
('I notice the good in a hard day too.', '7-9', 'gratitude', 202),
('I can watch and learn before I try.', '7-9', 'curiosity', 203),
('I belong wherever I am kind.', '7-9', 'belonging', 204),
('I share the game controller.', '7-9', 'teamwork', 205),
('I help my sister when mom asks me to.', '7-9', 'sibling-love', 206),
('I pack my own bag for school.', '7-9', 'responsibility', 207),
('Being brave means feeling scared and trying anyway.', '7-9', 'confidence', 208),
('I am worth the same as everybody else.', '7-9', 'self-worth', 209),
('I can start my work without being asked.', '7-9', 'independence', 210),
('I can be upset and still be okay.', '7-9', 'resilience', 211),
('My heart can feel many things at once.', '7-9', 'emotional-calm', 212),
('I can give a compliment every day.', '7-9', 'kindness-character', 213),
('I can sit with someone who is alone.', '7-9', 'friendship', 214),
('I am thankful for clean water to drink.', '7-9', 'gratitude', 215),
('My brain grows when I practice.', '7-9', 'curiosity', 216),
('My family is proud of who I am.', '7-9', 'belonging', 217),
('I help set the table for dinner.', '7-9', 'teamwork', 218),
('Nobody understands me like my sibling does.', '7-9', 'sibling-love', 219),
('I do my share of the work.', '7-9', 'responsibility', 220),
('I can join in even if I don''t know everyone.', '7-9', 'confidence', 221),
('I don''t need to be the best to matter.', '7-9', 'self-worth', 222),
('I can handle being on my own for a little while.', '7-9', 'independence', 223),
('I keep going even when it''s not fun.', '7-9', 'resilience', 224),
('I can be still and listen to my breath.', '7-9', 'emotional-calm', 225),
('I help my teacher by listening well.', '7-9', 'kindness-character', 226),
('I remember to include everyone.', '7-9', 'friendship', 227),
('I can write down what I''m thankful for.', '7-9', 'gratitude', 228),
('I wonder why the sky changes color.', '7-9', 'curiosity', 229),
('I am connected to the people who love me.', '7-9', 'belonging', 230),
('We solve problems together.', '7-9', 'teamwork', 231),
('I save the last cookie for my brother.', '7-9', 'sibling-love', 232),
('I follow through on what I say.', '7-9', 'responsibility', 233),
('My opinion counts.', '7-9', 'confidence', 234),
('I am a one-of-a-kind person.', '7-9', 'self-worth', 235),
('I can tie my shoes and zip my own coat.', '7-9', 'independence', 236),
('One bad grade doesn''t change who I am.', '7-9', 'resilience', 237),
('Crying when I''m sad is perfectly fine.', '7-9', 'emotional-calm', 238),
('I am gentle with animals and little kids.', '7-9', 'kindness-character', 239),
('I can say "let''s play something you like."', '7-9', 'friendship', 240),
('I am grateful for music and songs.', '7-9', 'gratitude', 241),
('I can ask the teacher when I''m curious.', '7-9', 'curiosity', 242),
('Home goes with me wherever I go.', '7-9', 'belonging', 243),
('I am kind to the new kid.', '7-9', 'teamwork', 244),
('My sister believes in me.', '7-9', 'sibling-love', 245),
('I keep my room tidy.', '7-9', 'responsibility', 246),
('I can do things that felt scary yesterday.', '7-9', 'confidence', 247),
('I can be happy being me.', '7-9', 'self-worth', 248),
('I make my bed because it''s my job.', '7-9', 'independence', 249),
('I can rebuild what fell apart.', '7-9', 'resilience', 250),
('I can choose a calm voice.', '7-9', 'emotional-calm', 251),
('I can let someone else go first.', '7-9', 'kindness-character', 252),
('A good friend shows up.', '7-9', 'friendship', 253),
('I notice when Mom or Dad does something nice.', '7-9', 'gratitude', 254),
('I like solving puzzles and riddles.', '7-9', 'curiosity', 255),
('I am an important part of my family.', '7-9', 'belonging', 256),
('I do my chores so my family can rest.', '7-9', 'teamwork', 257),
('We are different, and that is okay.', '7-9', 'sibling-love', 258),
('I handle my business.', '7-9', 'responsibility', 259),
('I am proud when I speak my mind kindly.', '7-9', 'confidence', 260),
('I don''t have to earn love by being perfect.', '7-9', 'self-worth', 261),
('I can choose what to do with my free time.', '7-9', 'independence', 262),
('I am tougher than I look.', '7-9', 'resilience', 263),
('Big feelings don''t last forever.', '7-9', 'emotional-calm', 264),
('Honesty is always the best choice.', '7-9', 'kindness-character', 265),
('I can make up with a friend after a fight.', '7-9', 'friendship', 266),
('I am thankful for my eyes that see colors.', '7-9', 'gratitude', 267),
('Every book teaches me something.', '7-9', 'curiosity', 268),
('Love finds me even on lonely days.', '7-9', 'belonging', 269),
('When my friend is sad, I sit with them.', '7-9', 'teamwork', 270),
('Home is better with my siblings in it.', '7-9', 'sibling-love', 271),
('I show up and do my part.', '7-9', 'responsibility', 272),
('I can lead and I can follow.', '7-9', 'confidence', 273),
('I am good enough right now.', '7-9', 'self-worth', 274),
('I can finish what I started.', '7-9', 'independence', 275),
('Crying is okay, and then I wipe my tears.', '7-9', 'resilience', 276),
('I can squeeze my pillow when I''m upset.', '7-9', 'emotional-calm', 277),
('I can make my family smile today.', '7-9', 'kindness-character', 278),
('I listen more than I talk sometimes.', '7-9', 'friendship', 279),
('I can say thank you before I eat.', '7-9', 'gratitude', 280),
('I can learn to do what my hero does.', '7-9', 'curiosity', 281),
('I fit in my family like a puzzle piece.', '7-9', 'belonging', 282),
('Asking for help is a brave thing to do.', '7-9', 'confidence', 283),
('My opinion of me matters most of all.', '7-9', 'self-worth', 284),
('I don''t give up just because no one is helping.', '7-9', 'independence', 285),
('I can start over as many times as I need.', '7-9', 'resilience', 286),
('I am safe even when I feel wobbly inside.', '7-9', 'emotional-calm', 287),
('I don''t say mean things, even as a joke.', '7-9', 'kindness-character', 288),
('I can make room for one more.', '7-9', 'friendship', 289),
('I am grateful for weekends with my family.', '7-9', 'gratitude', 290),
('I am excited to know more tomorrow.', '7-9', 'curiosity', 291),
('My family listens to me.', '7-9', 'belonging', 292),
('I can try a different way when the first way fails.', '7-9', 'confidence', 293),
('I am allowed to feel proud of myself.', '7-9', 'self-worth', 294),
('I can be on my own and feel okay.', '7-9', 'independence', 295),
('Problems are just puzzles I haven''t solved yet.', '7-9', 'resilience', 296),
('I can pause before I react.', '7-9', 'emotional-calm', 297),
('I can share my snack with a friend.', '7-9', 'kindness-character', 298),
('Friends help each other get better.', '7-9', 'friendship', 299),
('I notice the stars and the moon.', '7-9', 'gratitude', 300),
('I can explore outside and find new things.', '7-9', 'curiosity', 301),
('I am rooted like a strong tree.', '7-9', 'belonging', 302),
('I am getting stronger at being me.', '7-9', 'confidence', 303),
('Nobody else can be me, and that''s great.', '7-9', 'self-worth', 304),
('I am learning to take care of myself.', '7-9', 'independence', 305),
('I don''t let one bad moment ruin my day.', '7-9', 'resilience', 306),
('It''s okay to feel nervous before new things.', '7-9', 'emotional-calm', 307),
('I am the kind of person others can trust.', '7-9', 'kindness-character', 308),
('I can be patient when my friend is slow.', '7-9', 'friendship', 309),
('I am thankful for my school.', '7-9', 'gratitude', 310),
('I don''t have to know everything right now.', '7-9', 'curiosity', 311),
('We take care of each other.', '7-9', 'belonging', 312),
('I can show what I know.', '7-9', 'confidence', 313),
('I treat myself like I treat my friends.', '7-9', 'self-worth', 314),
('I can say no when something isn''t right.', '7-9', 'independence', 315),
('I can wait out the storm.', '7-9', 'resilience', 316),
('I can find my calm place inside me.', '7-9', 'emotional-calm', 317),
('I can do a secret good deed today.', '7-9', 'kindness-character', 318),
('I tell my friends what I appreciate about them.', '7-9', 'friendship', 319),
('I can thank my body for what it does.', '7-9', 'gratitude', 320),
('I can teach someone what I just learned.', '7-9', 'curiosity', 321),
('I am somebody''s whole world.', '7-9', 'belonging', 322),
('Confidence grows a little every day.', '7-9', 'confidence', 323),
('I am loved for who I am, not what I do.', '7-9', 'self-worth', 324),
('I trust myself to make good choices.', '7-9', 'independence', 325),
('Every day I get a little stronger.', '7-9', 'resilience', 326),
('Feelings are visitors; they don''t stay forever.', '7-9', 'emotional-calm', 327),
('Being kind is being strong.', '7-9', 'kindness-character', 328),
('I can start a conversation with a smile.', '7-9', 'friendship', 329),
('I end my day by naming one good thing.', '7-9', 'gratitude', 330),
('Being curious makes life fun.', '7-9', 'curiosity', 331),
('I carry my family''s love with me.', '7-9', 'belonging', 332);
